export const categoryConstants = {
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
	GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
	GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
	CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
	CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
	CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",
};

export const userConstants = {
	SIGNUP_REQUEST: "SIGNUP_REQUEST",
	SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
	SIGNUP_FAILURE: "SIGNUP_FAILURE",
	SIGNIN_REQUEST: "SIGNIN_REQUEST",
	SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
	SIGNIN_FAILURE: "SIGNIN_FAILURE",
};

export const questionConstants = {
	CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
	CREATE_QUESTION_FAILURE: "CREATE_QUESTION_FAILURE",
};
